# Override properties for Docker Compose environment
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce_db
    username: postgres
    password: postgres

  data:
    redis:
      host: redis

  kafka:
    bootstrap-servers: kafka:9092
